---
- name: Configurar Estação de Trabalho (Ubuntu)
  hosts: localhost
  connection: local

  vars:
    dotfiles_dir: "{{ ansible_facts.env.HOME }}/dotfiles"
    dotfiles_repo: "git@github.com:germanocorrea/dotfiles.git"
    python_packages:
      - "python3"
      - "python3-pip"
      - "python3-venv"

  tasks:
    - name: 1. Instalar pacotes base (Git, Stow)
      become: yes
      apt:
        name:
          - git
          - stow
          - curl
          - wget
          - build-essential
          - cmake
          - coreutils
        state: present
        update_cache: yes
      tags:
        - base
        - always

    - name: 2. Clonar repositório de dotfiles
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        version: main
        force: yes
      tags:
        - base
        - always

    - name: 4. Instalar Pacotes [development-base]
      become: yes
      apt:
        name:
          - speedtest-cli
        state: present
      tags:
        - packages
        - development-base

    - name: 6. Instalar Pacotes [personal]
      become: yes
      apt:
        name:
          - solaar
          - android-file-transfer
          - calibre
          - gimp
          - kdenlive
          - vlc
        state: present
      tags:
        - packages
        - personal

    - name: Configurar Neovim
      tags:
        - nvim
        - development-base
      block:
        - name: Instalar Neovim (via PPA para versão atualizada)
          become: yes
          block:
            - name: Adicionar PPA do Neovim
              ansible.builtin.apt_repository:
                repo: ppa:neovim-ppa/unstable
                state: present
            - name: Instalar Neovim
              apt:
                name: neovim
                state: present
          tags: packages

        - name: Aplicar (stow) dotfiles do Neovim
          command:
            cmd: "stow --adopt nvim"
            chdir: "{{ dotfiles_dir }}"
          tags: dotfiles

    - name: Configurar Zsh
      tags:
        - zsh
        - development-base
      block:
        - name: 1. Instalar pacote Zsh
          become: yes
          apt:
            name: zsh
            state: present
          tags: packages

        - name: 2. Trocar a shell padrão do usuário para zsh
          become: yes
          user:
            name: "{{ ansible_facts.user_id }}"
            shell: /usr/bin/zsh

        - name: 3. Instalar Oh My Zsh (Não-Interativo)
          shell:
            cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc'
            creates: "~/.oh-my-zsh"

        - name: 4. Instalar plugin zsh-syntax-highlighting
          git:
            repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
            dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

        - name: 5. Instalar plugin zsh-autosuggestions
          git:
            repo: "https://github.com/zsh-users/zsh-autosuggestions"
            dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

        - name: 6. Aplicar (stow) dotfiles do Zsh
          command:
            cmd: "stow --adopt zsh"
            chdir: "{{ dotfiles_dir }}"
          tags: dotfiles

    - name: Configurar Bash
      tags:
        - bash
        - development-base
      block:
        - name: Instalar pacote Bash
          become: yes
          apt:
            name: bash
            state: present
          tags: packages

        - name: Aplicar (stow) dotfiles do Bash
          command:
            cmd: "stow --adopt bash"
            chdir: "{{ dotfiles_dir }}"
          tags: dotfiles

    - name: Configurar Kitty
      tags:
        - kitty
        - personal
      block:
        - name: Instalar pacote Kitty
          become: yes
          apt:
            name: kitty
            state: present
          tags: packages

        - name: Aplicar (stow) dotfiles do Kitty
          command:
            cmd: "stow --adopt kitty"
            chdir: "{{ dotfiles_dir }}"
          tags: dotfiles

    - name: Configurar btop
      tags:
        - btop
        - personal
      block:
        - name: Instalar pacote btop
          become: yes
          apt:
            name: btop
            state: present
          tags: packages

        - name: Aplicar (stow) dotfiles do btop
          command:
            cmd: "stow --adopt btop"
            chdir: "{{ dotfiles_dir }}"
          tags: dotfiles

    - name: Instalar Haskell (GHCup)
      tags:
        - development-base
        - haskell
      block:
        - name: Baixar e instalar GHCup (Não-Interativo)
          ansible.builtin.shell:
            cmd: "curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh"
            creates: "~/.ghcup/bin/ghcup"
          environment:
            BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
        - name: Instalar fourmolu
          command:
            cmd: "cabal install fourmolu"
            creates: "~/.cabal/bin/fourmolu"

    - name: Instalar Rust (Rustup)
      tags:
        - development-base
        - rust
      block:
        - name: Baixar e instalar Rustup (Não-Interativo)
          ansible.builtin.shell:
            cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
            creates: "~/.cargo/bin/rustup"

    - name: Instalar NVM (Node Version Manager)
      tags:
        - nvm
        - development-base
      block:
        - name: Baixar e instalar NVM
          ansible.builtin.shell:
            cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash"
            creates: "~/.nvm/nvm.sh"

    - name: Instalar e configurar PHP
      tags:
        - development-base
        - php
      block:
        - name: Instalar pacote php
          become: yes
          apt:
            name: php
            state: present
          tags: packages

    - name: Instalação de Python e Pip
      become: yes
      apt:
        name: "{{ python_packages }}"
        state: present

    - name: Wallust
      command:
        cmd: cargo install wallust
        creates: "~/.cargo/bin/wallust"

    - name: Qobuz TUI
      command:
        cmd: cargo install --git https://github.com/SofusA/qobuz-player
        creates: "~/.cargo/bin/qobuz-player"

    - name: Restaurar estado original dos dotfiles (Garante que o repo vença o stow --adopt)
      command:
        cmd: "git checkout ."
        chdir: "{{ dotfiles_dir }}"
      tags:
        - dotfiles
        - always
