---
- name: Instalar pacotes base (Git, Stow)
  become: yes
  package:
    name:
      - git
      - stow
      - curl
      - wget
      - cmake
      - coreutils
    state: present
  tags:
    - base
    - always

- name: Clonar repositório de dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    version: main
    force: yes
  tags:
    - base
    - always
