---
- name: Instalar pacotes base (Git, Stow)
  become: yes
  package:
    name:
      - git
      - stow
      - curl
      - wget
      - cmake
      - coreutils
    state: present
  tags:
    - base
    - always
