---
- name: Instalar Haskell (GHCup)
  tags:
    - development-base
    - haskell
  block:
    - name: Baixar e instalar GHCup (Não-Interativo)
      ansible.builtin.shell:
        cmd: "curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh"
        creates: "~/.ghcup/bin/ghcup"
      environment:
        BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
- name: Instalar Rust (Rustup)
  tags:
    - development-base
    - rust
  block:
    - name: Baixar e instalar Rustup (Não-Interativo)
      ansible.builtin.shell:
        cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
        creates: "~/.cargo/bin/rustup"

- name: Instalar NVM (Node Version Manager)
  tags:
    - nvm
    - development-base
  block:
    - name: Baixar e instalar NVM
      ansible.builtin.shell:
        cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash"
        creates: "~/.nvm/nvm.sh"

    - name: Instalar TypeScript e typescript-language-server (npm)
      ansible.builtin.shell:
        cmd: "source ~/.nvm/nvm.sh && npm install -g typescript typescript-language-server"
        executable: /bin/bash
      tags: npm

- name: Instalar e configurar PHP
  tags:
    - development-base
    - php
  block:
    - name: Instalar pacote php
      become: yes
      package:
        name: php
        state: present
      tags: packages

    - name: Instalar composer
      become: yes
      package:
        name: composer
        state: present
      tags: packages

- name: Instalar Pacotes de Desenvolvimento via Pacman
  become: yes
  package:
    name:
      - hoogle
      - shfmt
      - shellcheck
    state: present
  tags:
    - packages
    - development-base

- name: Instalar nixfmt (nix profile)
  ansible.builtin.shell:
    cmd: "nix profile install nixpkgs#nixfmt-rfc-style"
  tags:
    - development-base
    - nix

- name: Instalar dockfmt (go install)
  ansible.builtin.shell:
    cmd: "go install github.com/jessfraz/dockfmt@latest"
    creates: "~/go/bin/dockfmt"
  tags:
    - development-base
    - go

- name: Instalar gomodifytags (go install)
  ansible.builtin.shell:
    cmd: "go install github.com/fatih/gomodifytags@latest"
    creates: "~/go/bin/gomodifytags"
  tags:
    - development-base
    - go
