---
- name: Instalação de Python e Pip
  become: yes
  package:
    name: "{{ python_packages[ansible_facts['distribution']] }}"
    state: present
  vars:
    python_packages:
      Archlinux:
        - "python"
        - "python-pip"
      CachyOS:
        - "python"
        - "python-pip"
