---
- name: Instalação de Python e Pip
  become: yes
  package:
    name: "{{ python_packages[ansible_facts['distribution']] }}"
    state: present
  vars:
    python_packages:
      Archlinux:
        - "python"
        - "python-pip"
        - "python-pipx"
      CachyOS:
        - "python"
        - "python-pip"
        - "python-pipx"

- name: Instalar gdtoolkit via pipx
  command:
    cmd: 'pipx install "gdtoolkit==4.*"'
    creates: "~/.local/bin/gdformat"
