"use strict";var E=Object.create;var d=Object.defineProperty;var v=Object.getOwnPropertyDescriptor;var F=Object.getOwnPropertyNames;var _=Object.getPrototypeOf,N=Object.prototype.hasOwnProperty;var q=(e,t)=>{for(var r in t)d(e,r,{get:t[r],enumerable:!0})},P=(e,t,r,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of F(t))!N.call(e,i)&&i!==r&&d(e,i,{get:()=>t[i],enumerable:!(n=v(t,i))||n.enumerable});return e};var U=(e,t,r)=>(r=e!=null?E(_(e)):{},P(t||!e||!e.__esModule?d(r,"default",{value:e,enumerable:!0}):r,e)),D=e=>P(d({},"__esModule",{value:!0}),e);var O={};q(O,{default:()=>b});module.exports=D(O);var T=require("@vicinae/api");var y=require("@vicinae/api"),g=require("react");var S=require("node:child_process"),x=U(require("node:util")),a=x.default.promisify(S.exec);var k=require("react"),L=require("react/jsx-runtime"),A=({onSuccess:e,onFail:t,command:r})=>{let[n,i]=(0,g.useState)(!0),[m,f]=(0,g.useState)(!1);return(0,k.useEffect)(()=>{a(r).then(({stdout:s,stderr:p})=>{f(s.trim()!==""&&p.trim()==="")}).catch(()=>{f(!1)}).finally(()=>{i(!1)})},[]),n?(0,L.jsx)(y.List,{isLoading:!0}):m?e:t};var l=require("react"),o=require("@vicinae/api");var C=async()=>{let{stdout:e}=await a("powerprofilesctl list"),t=new Set(e.split(`

`).map(r=>r.split(`
`)[0].replace("*","").replace(":","").replace(" ","").trim()).filter(r=>r&&r!==""));return Array.from(t)},I=async(e,t)=>await Promise.race([a(`powerprofilesctl set ${e}`).then(()=>"done"),new Promise(r=>setTimeout(r,t)).then(()=>"timeout")]),h=async()=>{let{stdout:e}=await a("powerprofilesctl get");return e.trim()};var c=require("react/jsx-runtime"),M=2e3,R=()=>{let[e,t]=(0,l.useState)(!0),[r,n]=(0,l.useState)([]),[i,m]=(0,l.useState)(""),f=async s=>{let p=i;if(await I(s,M)==="timeout"){(0,o.showToast)({title:"Timeout",message:"The profile change timed out, is the power-profiles-daemon running?",style:o.Toast.Style.Failure});return}let w=await h();if(w===p){(0,o.showToast)({title:"The profile change failed",style:o.Toast.Style.Failure});return}(0,o.showToast)({title:"Success",style:o.Toast.Style.Success}),m(w)};return(0,l.useEffect)(()=>{Promise.all([C(),h()]).then(([s,p])=>{n(s),m(p),t(!1)})},[]),(0,c.jsx)(o.List,{isLoading:e,searchBarPlaceholder:"Select your power profile...",children:(0,c.jsx)(o.List.Section,{title:"Profiles",children:r.map(s=>(0,c.jsx)(o.List.Item,{title:s,icon:s===i?o.Icon.Checkmark:o.Icon.Cog,keywords:[s],actions:(0,c.jsx)(o.ActionPanel,{children:(0,c.jsx)(o.Action,{title:"Select",icon:o.Icon.Cog,onAction:()=>f(s)})})},s))})})};var u=require("react/jsx-runtime");function b(){return(0,u.jsx)(A,{command:"powerprofilesctl",onSuccess:(0,u.jsx)(R,{}),onFail:(0,u.jsx)(T.Detail,{markdown:`
# Please install \`power-profiles-daemon\` to use this extension

- Upstream URL (with docs): [https://gitlab.freedesktop.org/upower/power-profiles-daemon](https://gitlab.freedesktop.org/upower/power-profiles-daemon)
- Arch package: [https://archlinux.org/packages/extra/x86_64/power-profiles-daemon/](https://archlinux.org/packages/extra/x86_64/power-profiles-daemon/)
- Nix package: [https://search.nixos.org/packages?channel=25.05&show=power-profiles-daemon&query=power-profiles-daemon](https://search.nixos.org/packages?channel=25.05&show=power-profiles-daemon&query=power-profiles-daemon)
- Debian package: [https://packages.debian.org/sid/power-profiles-daemon](https://packages.debian.org/sid/power-profiles-daemon)
`})})}
