;;; doom-jetbrains-islands-dark-theme.el --- Ported from Zed theme -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; Author: Generated by zed2doom.py, opencode and github.com/germanocorrea
;; Keywords: custom themes, faces
;;
;;; Commentary:
;;
;; Ported from Zed editor theme "JetBrains Islands Dark" by Artem Evsevev.
;;
;;; Code:

(require 'doom-themes)

;;; Options
(defgroup doom-jetbrains-islands-dark nil
  "Options for the `doom-jetbrains-islands-dark' theme."
  :group 'doom-themes)

(defcustom doom-jetbrains-islands-dark-brighter-modeline nil
  "If non-nil, more vivid colors will be used to style the mode-line."
  :group 'doom-jetbrains-islands-dark
  :type 'boolean)

(defcustom doom-jetbrains-islands-dark-brighter-comments nil
  "If non-nil, comments will be highlighted in more vivid colors."
  :group 'doom-jetbrains-islands-dark
  :type 'boolean)

(defcustom doom-jetbrains-islands-dark-padded-modeline doom-themes-padded-modeline
  "If non-nil, adds a padding to the mode-line.
Can be an integer to determine the exact padding."
  :group 'doom-jetbrains-islands-dark
  :type '(choice integer boolean))

;;; Theme definition
(def-doom-theme doom-jetbrains-islands-dark
    "JetBrains Islands Dark theme (ported from Zed)"
  :background-mode 'dark

  ;; name        default           256               16
  (
   (bg          '("#191A1C"           "#191A1C"            "black"            ))
   (fg          '("#bcbec4"           "#bcbec4"            "cyan"            ))
   (bg-alt      '("#1F2024"       "#1F2024"        "brightblack"        ))
   (fg-alt      '("#bcbec4"           "#bcbec4"            "white"                     ))

   (base0       '("#191A1C"        "#191A1C"         "black"         ))
   (base1       '("#171719"        "#171719"         "black"         ))
   (base2       '("#18181a"        "#18181a"         "black"         ))
   (base3       '("#191A1C"        "#191A1C"         "black"         ))
   (base4       '("#7a7e85"        "#7a7e85"         "brightblack"         ))
   (base5       '("#4b5059"        "#4b5059"         "brightblack"         ))
   (base6       '("#9ea3ac"        "#9ea3ac"         "cyan"         ))
   (base7       '("#838589"        "#838589"         "brightblack"         ))
   (base8       '("#bcbec4"        "#bcbec4"         "cyan"         ))

   (grey        base4)
   (red         '("#fa6675"   "#fa6675"    "brightblack"   ))
   (orange      '("#cf8e6d"      "#cf8e6d"       "brightblack"      ))
   (green       '("#6aab73"       "#6aab73"        "green"       ))
   (teal        '("#20999D"       "#20999D"        "cyan"       ))
   (yellow      '("#6DA1AB"         "#6DA1AB"          "cyan"         ))
   (blue        '("#56A8F5"     "#56A8F5"      "cyan"     ))
   (dark-blue   '("#5594fa"     "#5594fa"      "cyan"     ))
   (magenta     '("#c77dbb"     "#c77dbb"      "magenta"     ))
   (violet      '("#bcbec4"     "#bcbec4"      "cyan"     ))
   (cyan        '("#47ccbd"     "#47ccbd"      "cyan"     ))
   (dark-cyan   '("#4EADE5" "#4EADE5" "cyan"))

   ;; Default categories
   (highlight      blue)
   (vertical-bar   base1)
   (selection      "#214283")
   (builtin        blue)
   (comments       grey)
   (doc-comments   "#5f826b")
   (constants      magenta)
   (functions      blue)
   (keywords       orange)
   (methods        cyan)
   (operators      fg)
   (type           yellow)
   (strings        green)
   (variables      violet)
   (numbers        teal)
   (region         "#214283")
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    "#375fad")
   (vc-added       green)
   (vc-deleted     red)

   ;; Extra
   (line-number       "#4b5059")
   (line-number-current "#a1a3ab")

   ;; Modeline
   (modeline-bg          "#26282c")
   (modeline-bg-alt      "#26282c")
   (modeline-bg-inactive "#202225")
   (modeline-fg          fg)
   (modeline-fg-alt      "#7a7e85")
   (modeline-fg-inactive base5)

   ;; Org headings
   (org-level-1 functions)
   (org-level-2 constants)
   (org-level-3 green)
   (org-level-4 orange)
   (org-level-5 magenta)
   (org-level-6 cyan)
   (org-level-7 type)
   (org-level-8 variables))

  ;; Face overrides
  (
   ((font-lock-comment-face &override)
    :foreground comments
    :slant 'italic)

   ((font-lock-doc-face &override)
    :foreground doc-comments
    :slant 'italic)

   ((font-lock-keyword-face &override)
    :foreground keywords)

   ((font-lock-string-face &override)
    :foreground strings)

   ((font-lock-function-name-face &override)
    :foreground functions)

   ((font-lock-builtin-face &override)
    :foreground blue
    :slant 'italic)

   ((font-lock-variable-name-face &override)
    :foreground variables)

   ((font-lock-type-face &override)
    :foreground type)

   ((font-lock-constant-face &override)
    :foreground constants)

   ((font-lock-number-face &override)
    :foreground numbers)

   ((default &override)
    :foreground fg :background bg)

   ;; Line numbers
   ((line-number &override) :foreground line-number)
   ((line-number-current-line &override) :foreground line-number-current)

   ;; Highlight line
   (hl-line :background "#1F2024")

   ;; Region / selection
   ((region &override) :background "#214283" :extend t)

   ;; Search
   (isearch :background "#2D543F" :foreground fg :weight 'bold)
   (lazy-highlight :background "#114957" :foreground fg)
   ((isearch-fail &override) :background "#fa6675" :foreground fg)

   ;; Fill column indicator
   (fill-column-indicator :foreground "#393b40" :height 1)

   ;; Mode line
   (mode-line
    :background "#26282c"
    :foreground fg
    :box (if doom-jetbrains-islands-dark-padded-modeline
             `(:line-width ,doom-jetbrains-islands-dark-padded-modeline :color ,"#26282c")))
   (mode-line-inactive
    :background "#202225"
    :foreground base5
    :box (if doom-jetbrains-islands-dark-padded-modeline
             `(:line-width ,doom-jetbrains-islands-dark-padded-modeline :color ,"#202225")))
   (mode-line-emphasis :foreground fg :weight 'bold)

   ;; Doom modeline
   (doom-modeline-bar :background green)
   (doom-modeline-evil-emacs-state  :foreground magenta)
   (doom-modeline-evil-normal-state :foreground green)
   (doom-modeline-evil-visual-state :foreground magenta)
   (doom-modeline-evil-insert-state :foreground orange)

   ;; Solaire mode line
   (solaire-mode-line-face
    :inherit 'mode-line
    :background (doom-lighten "#26282c" 0.15)
    :box (if doom-jetbrains-islands-dark-padded-modeline
             `(:line-width ,doom-jetbrains-islands-dark-padded-modeline :color ,(doom-lighten "#26282c" 0.15))))
   (solaire-mode-line-inactive-face
    :inherit 'mode-line-inactive
    :background (doom-darken "#202225" 0.1)
    :box (if doom-jetbrains-islands-dark-padded-modeline
             `(:line-width ,doom-jetbrains-islands-dark-padded-modeline :color ,(doom-darken "#202225" 0.1))))

   ;; Company
   (company-tooltip-selection :background blue :foreground bg)
   (company-tooltip :background bg-alt :foreground fg)

   ;; Ivy
   (ivy-current-match :background bg-alt :distant-foreground fg :weight 'bold)
   (ivy-minibuffer-match-face-1 :foreground green :weight 'bold)
   (ivy-minibuffer-match-face-2 :foreground constants :weight 'bold)
   (ivy-minibuffer-match-face-3 :foreground orange :weight 'bold)
   (ivy-minibuffer-match-face-4 :foreground magenta :weight 'bold)
   (ivy-match-highlight :foreground blue :weight 'bold)

   ;; Helm
   (helm-selection :background bg-alt :foreground fg :weight 'bold)

   ;; CSS mode
   (css-proprietary-property :foreground orange)
   (css-property :foreground green)
   (css-selector :foreground green)

   ;; Org
   (org-level-1 :foreground functions)
   (org-level-2 :foreground constants)
   (org-level-3 :foreground green)
   (org-level-4 :foreground orange)
   (org-level-5 :foreground magenta)
   (org-level-6 :foreground cyan)
   (org-level-7 :foreground type)
   (org-level-8 :foreground variables)
   (org-block :background (doom-darken bg 0.04) :extend t)
   (org-block-background :background (doom-darken bg 0.04))
   (org-block-begin-line :background (doom-darken bg 0.08) :foreground comments :extend t)
   (org-block-end-line :background (doom-darken bg 0.08) :foreground comments :extend t)
   (org-special-keyword :foreground keywords)
   (org-tag :foreground doc-comments :weight 'bold)

   ;; Markdown
   (markdown-markup-face :foreground fg)
   (markdown-header-face :inherit 'bold :foreground red)
   (markdown-inline-face :foreground fg)
   ((markdown-code-face &override) :background (doom-darken bg 0.04))

   ;; Widget
   (widget-field :foreground fg :background bg-alt)
   (widget-single-line-field :foreground fg :background bg-alt)

   ;; Swiper
   (swiper-match-face-1 :foreground green :weight 'bold)
   (swiper-match-face-2 :foreground constants :weight 'bold)
   (swiper-match-face-3 :foreground orange :weight 'bold)
   (swiper-match-face-4 :foreground magenta :weight 'bold)
   (swiper-line-face :background bg-alt :foreground fg)

   ;; Diff
   (diff-added :foreground vc-added :extend t)
   (diff-removed :foreground vc-deleted :extend t)
   (diff-changed :foreground vc-modified :extend t)
   (diff-refine-added :foreground green :background (doom-darken bg 0.1) :extend t)
   (diff-refine-removed :foreground red :background (doom-darken bg 0.1) :extend t)
   (diff-refine-changed :foreground yellow :background (doom-darken bg 0.1) :extend t)

   ;; LSP / Document highlights
   ((lsp-face-document-highlight-read &override) :background "#373b39" :extend t)
   ((lsp-face-document-highlight-write &override) :background "#402f33" :extend t)))

(provide 'doom-jetbrains-islands-dark-theme)
;;; doom-jetbrains-islands-dark-theme.el ends here
