# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #7C7F85

background #000102
foreground #B4B3B8

color0 #000203
color1 #122127
color2 #21393C
color3 #1F273F
color4 #41283B
color5 #2D3E52
color6 #433C61
color7 #9E9DA2
color8 #6B696F
color9 #122127
color10 #21393C
color11 #1F273F
color12 #41283B
color13 #2D3E52
color14 #433C61
color15 #C6C5C8

mark1_foreground #393061
mark2_foreground #857EA2
mark3_foreground #393061
