# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #D39A9E

background #080310
foreground #B0AAB9

color0 #484246
color1 #412B63
color2 #8F3459
color3 #D42C42
color4 #8D4C90
color5 #F76055
color6 #DB78C1
color7 #857D92
color8 #5D5766
color9 #412B63
color10 #8F3459
color11 #D42C42
color12 #8D4C90
color13 #F76055
color14 #DB78C1
color15 #857D92

mark1_foreground #DB60BB
mark2_foreground #766492
mark3_foreground #DB60BB
